-- AlterTable
ALTER TABLE `Order` ADD COLUMN `orderSource` ENUM('DIRECT', 'CART') NOT NULL DEFAULT 'DIRECT',
    ADD COLUMN `sourceScreen` VARCHAR(50) NULL;

-- AlterTable
ALTER TABLE `OrderItem` ADD COLUMN `fromWishlist` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `PurchaseJourney` ADD COLUMN `addedFromScreen` VARCHAR(50) NULL,
    ADD COLUMN `wasInWishlist` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `WishlistActivity` MODIFY `eventType` ENUM('ADD_TO_WISHLIST', 'REMOVE_FROM_WISHLIST', 'MOVE_TO_CART', 'RESTORE_TO_WISHLIST', 'CLEAR_WISHLIST', 'MERGED_FROM_GUEST', 'MERGED_TO_USER', 'AUTO_REMOVE_PRODUCT', 'AUTO_REMOVE_VARIANT', 'ORDER_CREATED') NOT NULL;

-- AlterTable
ALTER TABLE `WishlistItem` ADD COLUMN `convertedAt` DATETIME(3) NULL,
    ADD COLUMN `convertedUserId` INTEGER NULL,
    ADD COLUMN `firstAddedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `originalGuestId` VARCHAR(191) NULL,
    ADD COLUMN `originallyAddedBy` ENUM('GUEST', 'USER') NOT NULL DEFAULT 'USER';
